FROM node:14-alpine AS build-env
RUN mkdir -p /usr/src/hexo-blog
WORKDIR /usr/src/hexo-blog
COPY . .
RUN npm install hexo-cli -g && npm install
RUN hexo clean && hexo g

FROM caddy:latest
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY ./Caddyfile /etc/caddy/Caddyfile
COPY --from=build-env /usr/src/hexo-blog/public /srv